/*
 * Cloud Avenue API
 *
 * Cloud Avenue API allows you to create some ressources on vCloud Director. ## Authentication In order to authenticate to this API, you must first authenticate through vCloudDirector API using **POST https://{{api_host}}/cloudapi/1.0.0/sessions**. Then use _X-VMWARE-VCLOUD-ACCESS-TOKEN_ from response header in your request.  If you need more information do not hesitate to read our dedicated page on [our Wiki](https://wiki.cloudavenue.orange-business.com/w/index.php/API_Cloud_Avenue) 
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cloudavenue

type Pesg struct {
	// internal object identifier
	Id string `json:"id,omitempty"`
	// This action implies the creation of a Logical Switch and an External Network.
	Name string `json:"name,omitempty"`
	// For external customers `ADMIN`, `INET`. <br/> For internal customers `PFS`, `RBCI`, `EIN`, `EXPL`, `ST`, `GINIS`, `GINEFA`, `GINCMZ`, `NFS`, `BACKUP`.
	Type_ string `json:"type"`
	// Contains public-ip in case of INET PESG and the associated network mask
	IntercoIp string `json:"intercoIp,omitempty"`
	// Only and required for NFS PESG
	VlanId int32 `json:"vlanId,omitempty"`
	// Internal Ip connected with associated network mmask (will be the one belonging to the external network of the organization)
	InternalIp string `json:"internalIp,omitempty"`
	NetworkConfig *[]NetworkConfigInner `json:"networkConfig,omitempty"`
}
