/*
 * Cloud Avenue API
 *
 * Cloud Avenue API allows you to create some ressources on vCloud Director. ## Authentication In order to authenticate to this API, you must first authenticate through vCloudDirector API using **POST https://{{api_host}}/cloudapi/1.0.0/sessions**. Then use _X-VMWARE-VCLOUD-ACCESS-TOKEN_ from response header in your request.  If you need more information do not hesitate to read our dedicated page on [our Wiki](https://wiki.cloudavenue.orange-business.com/w/index.php/API_Cloud_Avenue) 
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StorageProfile struct {
	// VMware unique ID. There is no ID in the body of the POST request, as VMware which generates it. This ID must be present for GET and PUT.
	Id string `json:"id,omitempty"`
	Name string `json:"name"`
	// Max number of units allocated for this storage profile. In Gb
	Limit int32 `json:"limit"`
	// Current usage of this StorageProfile in Gb. Deletion is allowed only if there is no usage of the StorageProfile
	Used int32 `json:"used,omitempty"`
	Default_ bool `json:"default,omitempty"`
}
