/*
 * Cloud Avenue API
 *
 * Cloud Avenue API allows you to create some ressources on vCloud Director. ## Authentication In order to authenticate to this API, you must first authenticate through vCloudDirector API using **POST https://{{api_host}}/cloudapi/1.0.0/sessions**. Then use _X-VMWARE-VCLOUD-ACCESS-TOKEN_ from response header in your request.  If you need more information do not hesitate to read our dedicated page on [our Wiki](https://wiki.cloudavenue.orange-business.com/w/index.php/API_Cloud_Avenue) 
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cloudavenue
// Tier0VrfClassOfService : Class of service wanted on Tier-0 VRF Gateway
type Tier0VrfClassOfService string

// List of tier0VRFClassOfService
const (
	SHARED_STANDARD_Tier0VrfClassOfService Tier0VrfClassOfService = "SHARED_STANDARD"
	SHARED_PREMIUM_Tier0VrfClassOfService Tier0VrfClassOfService = "SHARED_PREMIUM"
	DEDICATED_MEDIUM_Tier0VrfClassOfService Tier0VrfClassOfService = "DEDICATED_MEDIUM"
	DEDICATED_LARGE_Tier0VrfClassOfService Tier0VrfClassOfService = "DEDICATED_LARGE"
)
