---
name: Generate SDK from distant swagger

on:
  workflow_dispatch:
  schedule:
    - cron: "44 4 * * *"

jobs:
  remote_swagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: wget
        uses: wei/wget@v1
        with:
          args: -O NGP_Api_for_Customer_Cloud_Avenue.yml https://swagger.cloudavenue.orange-business.com/doc/NGP_Api_for_Customer_Cloud_Avenue.yml
      - name: check md5 swagger file
        run: |
          if [[ -f NGP_Api_for_Customer_Cloud_Avenue.yml.md5 && $(cat NGP_Api_for_Customer_Cloud_Avenue.yml.md5) == $(md5sum NGP_Api_for_Customer_Cloud_Avenue.yml | awk '{print $1}') ]]; then echo "Swagger File is unchanged; exit 1" ; else md5sum NGP_Api_for_Customer_Cloud_Avenue.yml | awk '{print $1}' > NGP_Api_for_Customer_Cloud_Avenue.yml.md5 ; fi
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: NGP_Api_for_Customer_Cloud_Avenue.yml
      - name: Swagger Codegen v3
        uses: CapsLock-Studio/swagger-codegen-action@v1
        with:
          args: |
            generate --lang go --input-spec NGP_Api_for_Customer_Cloud_Avenue.yml
      - name: change authorization
        run: |
          sudo chmod -R 777 *
          sudo chmod -R 777 .swagger-codegen
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update godaddy-domains
          title: Update godaddy-domains
          body: |
            Update godaddy-domains
            Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: dependencies, automated pr
          branch: swagger-codegen